version: '3.8'

services:

  api:
    image: henrikklev/swiftgift-api:latest
    container_name: swiftgift-api
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gaveliste
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

  image_db:
    image: postgres:latest
    container_name: images_postgres_db
    environment:
      POSTGRES_USER: ${IMG_DB_USER}
      POSTGRES_PASSWORD: ${IMG_DB_PASSWORD}
      POSTGRES_DB: swiftgift_images
    ports:
      - "5433:5432"
    volumes:
      - db_images:/var/lib/postgresql/images

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    network_mode: host
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - certbot

volumes:
  db_data:
  db_images:
