name: Build application & upload artifact

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4
    - name: Build with Gradle Wrapper
      run: ./gradlew buildFatJar

    - name: Rename JAR
      run: mv build/libs/swiftgift-api-all.jar swiftgift-api.jar

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with: 
        name: SwiftGift API Jar
        path: swiftgift-api.jar
        if-no-files-found: error
        overwrite: true

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@4
